#!/bin/sh

#########################################################
#########################################################
##### ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗ #####
##### ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║ #####
##### ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║ #####
##### ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║ #####
##### ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║ #####
##### ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝ #####
#########################################################
#########################################################

launcher &
xsetroot -cursor_name left_ptr &
sudo chown xzecora /dev/input/by-id/usb-mayflash_limited_MAYFLASH_GameCube_Controller_Adapter-event-joystick &
#xrandr --output DP-0 --primary && nvidia-settings --assign CurrentMetaMode="HDMI-0: nvidia-auto-select +2560+152 {ForceCompositionPipeline=On}, DP-0: 2560x1440_165 +0+0 {ForceCompositionPipeline=On}" &


bspc monitor DP-0 -d I III IV V VI 
bspc monitor HDMI-0 -d II  VII VIII IX X

bspc config border_width         4
bspc config window_gap           12

wal -R
. "${HOME}/.cache/wal/colors.sh"

bspc config active_border_color "$color1"
bspc config normal_border_color "$color2"
bspc config focused_border_color "$color3"
bspc config presel_feedback_color "$color4"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
bspc rule -a Spotify desktop='^7'
bspc rule -a discord desktop='^6'

~/.config/polybar/launch.sh
